apiVersion: v1
kind: Service
metadata:
  name: project-service
  namespace: default
spec:
  selector:
    app: flowforge-project-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
