apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowforge-analysis-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flowforge-analysis-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
      labels:
        tier: backend
        app: flowforge-analysis-service
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: flowforge-analysis-service
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001

      containers:
        - name: analysis-service
          image: "flowforgeacrm9mp04.azurecr.io/flowforge/analysis-service:07f448b"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8004

          envFrom:
            - configMapRef:
                name: flowforge-config

          env:
            - name: APP_PORT
              value: "8004"
            - name: GATEWAY_PORT
              value: "8004"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 8004
            initialDelaySeconds: 5
            periodSeconds: 10

      nodeSelector:
        agentpool: node1
