apiVersion: v1
kind: ServiceAccount
metadata:
  name: flowforge-analysis-service
  namespace: default
  annotations:
    azure.workload.identity/client-id: "978c249b-1ac1-475a-9138-e96be1ec0f44"
automountServiceAccountToken: false
