replicaCount: 1

image:
  repository: ghcr.io/noel-mathews-org/flowforge/notification-worker
  tag: latest
  pullPolicy: IfNotPresent

resources:
  requests:
    cpu: 15m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 192Mi
