global:
  namespace: flowforge
  environment: dev
  domain: flowforge.fun
  azure:
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
    keyvaultName: "kv-dev-ff-001"
    keyvaultUrl: "https://kv-dev-ff-001.vault.azure.net/"
    managedIdentityClientId: "b0f1c302-e938-4fb2-be9d-efbf5c02d9bb"
  entra:
    clientId: "668b4772-3c2e-4b86-98e0-04c58199cfe5"
  ai:
    deployment: "summary-agent"
  storage:
    accountName: "stffdev001"
    container: "app-data"
gateway:
  enabled: true
  image:
    tag: 2be66ca
frontend:
  enabled: true
  image:
    tag: d7d1340
auth-service:
  enabled: true
  image:
    tag: 17c8e62
project-service:
  enabled: true
  image:
    tag: 0037d90
task-service:
  enabled: true
  image:
    tag: 0037d90
analysis-service:
  enabled: true
  image:
    tag: 98bc831
notification-worker:
  enabled: true
  image:
    tag: 2be66ca
