global:
  namespace: flowforge
  environment: dev
  domain: flowforge.fun
  azure:
    tenantId: "bed24716-6a89-4b1d-96ff-3522f4dfa9c1"
    keyvaultName: "kv-dev-0nedgn"
    keyvaultUrl: "https://kv-dev-0nedgn.vault.azure.net"
    managedIdentityClientId: "1d033315-c66f-428f-b5a0-bfe65e488856"
  entra:
    clientId: "7cd2b208-eee0-40be-b2c5-7254a73b6b18"
  ai:
    deployment: "summary-agent"
  storage:
    accountName: "sadev0nedgn"
    container: "reports"
gateway:
  enabled: true
  image:
    tag: 6ee465f
frontend:
  enabled: true
  image:
    tag: 6ee465f
auth-service:
  enabled: true
  image:
    tag: 6ee465f
project-service:
  enabled: true
  image:
    tag: 6ee465f
task-service:
  enabled: true
  image:
    tag: c080724
analysis-service:
  enabled: true
  image:
    tag: 6ee465f
notification-worker:
  enabled: true
  image:
    tag: 2be66ca
