global:
  environment: prod
  domain: flowforge.fun

gateway:
  enabled: true
frontend:
  enabled: true
auth-service:
  enabled: true
project-service:
  enabled: true
task-service:
  enabled: true
analysis-service:
  enabled: true
