global:
  namespace: flowforge
  environment: prod
  domain: flowforge.fun
  azure:
    tenantId: "9b268e03-4db3-41c1-9c63-c106982f5abd"
    keyvaultName: "c573z-ff-prod"
    keyvaultUrl: "https://c573z-ff-prod.vault.azure.net/"
    managedIdentityClientId: "814a02a8-bfd4-41ca-b29d-2bc4b3e06416"
  entra:
    clientId: "efc06b91-6db5-4716-9811-a40385914c6c"
  storage:
    accountName: "c573zffprod"
gateway:
  enabled: true
  image:
    tag: v2.0.0
frontend:
  enabled: true
  image:
    tag: v2.0.1
auth-service:
  enabled: true
  image:
    tag: v2.0.0
project-service:
  enabled: true
  image:
    tag: v2.0.0
task-service:
  enabled: true
  image:
    tag: v2.0.0
analysis-service:
  enabled: true
  image:
    tag: v2.0.0
notification-worker:
  enabled: true
  image:
    tag: v1.1.0

