apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-sa
  namespace: {{ .Release.Namespace }}
  annotations:
    azure.workload.identity/client-id: {{ .Values.global.azure.otelClientId }}
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: flowforge-otel
  namespace: {{ .Release.Namespace }}
spec:
  mode: deployment
  serviceAccount: otel-collector-sa
  podAnnotations:
    azure.workload.identity/use: "true"
  podLabels:
    azure.workload.identity/use: "true"
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      azuremonitor:
        connection_string: {{ .Values.global.azure.appInsightsConnectionString }}
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [azuremonitor]
        metrics:
          receivers: [otlp]
          exporters: [azuremonitor]
        logs:
          receivers: [otlp]
          exporters: [azuremonitor]
