apiVersion: v1
kind: ServiceAccount
metadata:
  name: otel-collector-sa
  namespace: flowforge-prod
  annotations:
    azure.workload.identity/client-id: "c36adeaf-f346-4ffb-9b87-73309e4678d9"
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: flowforge-otel
  namespace: flowforge-prod
  labels:
    azure.workload.identity/use: "true"
spec:
  mode: deployment
  image: "otel/opentelemetry-collector-contrib:latest"
  serviceAccount: otel-collector-sa
  podAnnotations:
    azure.workload.identity/use: "true"
  config:
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
    exporters:
      azuremonitor:
        connection_string: "InstrumentationKey=088eb5e8-088f-425f-8b48-51e2fd8b46b4;IngestionEndpoint=https://centralindia-0.in.applicationinsights.azure.com/;LiveEndpoint=https://centralindia.livediagnostics.monitor.azure.com/;ApplicationId=8c6f9076-ad2a-4314-aa6e-ed3278d7bc51"
    service:
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [azuremonitor]
        metrics:
          receivers: [otlp]
          exporters: [azuremonitor]
        logs:
          receivers: [otlp]
          exporters: [azuremonitor]

---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: flowforge-instrumentation
  namespace: flowforge-prod
spec:
  exporter:
    endpoint: http://flowforge-otel-collector:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: always_on
