apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-prod
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
      chart: opentelemetry-collector
      targetRevision: 0.87.1
      helm:
        valueFiles:
          - $values/infra/otel-prod.yaml
    - repoURL: 'https://github.com/Noel-Mathews-Org/FlowForge-Helm.git'
      targetRevision: Cloud-Track-dev
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: flowforge-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
