apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowforge-frontend
  namespace: default
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: flowforge-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-nodejs: "true"
      labels:
        tier: frontend
        app: flowforge-frontend
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: flowforge-frontend
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001

      containers:
        - name: frontend
          image: "flowforgeacrm9mp04.azurecr.io/flowforge/frontend:47b4d87"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: flowforge-config

          env:
            - name: APP_PORT
              value: "3000"
            - name: GATEWAY_PORT
              value: "3000"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10

      nodeSelector:
        agentpool: node1
