apiVersion: v1
kind: ServiceAccount
metadata:
  name: flowforge-auth-service
  namespace: default
  annotations:
    azure.workload.identity/client-id: "4b6676e9-5bf5-4f04-b5b7-83cf166d1bf3"
automountServiceAccountToken: false
