apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Noel-Mathews-Org/FlowForge-Helm.git
    targetRevision: Cloud-Track-dev
    path: infra
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

