apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flowforge-routes
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: flowforge-gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: gateway
      port: 80
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: frontend
      port: 80
