apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None # Headless Service
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: {{ .Release.Namespace }}
spec:
  serviceName: "postgres"
  replicas: 1
  minReadySeconds: 15
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        tier: data
        app: postgres
    spec:
      securityContext:
        fsGroup: 70
      containers:
      - name: postgres
        image: postgres:16-alpine
        securityContext:
          runAsNonRoot: true
          runAsUser: 70
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        ports:
        - containerPort: 5432
        startupProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          initialDelaySeconds: 10
          failureThreshold: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", "postgres"]
          periodSeconds: 10
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: flowforge-secret
              key: DATABASE_PASSWORD
        - name: POSTGRES_DB
          value: "flowforge"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        - name: initdb-volume
          mountPath: /docker-entrypoint-initdb.d/initdb.sql
          subPath: initdb.sql
          readOnly: true
      volumes:
      - name: initdb-volume
        configMap:
          name: postgres-initdb
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-csi"
      resources:
        requests:
          storage: 10Gi
