global:
  namespace: flowforge-dev
  environment: dev
  domain: dev.flowforge.fun
  azure:
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
    keyvaultUrl: "https://kvlt-dev-40xtuj.vault.azure.net/"
    managedIdentityClientId: "4b6676e9-5bf5-4f04-b5b7-83cf166d1bf3"
    managedIdentityName: "mi-flowforge-app-dev"
  entra:
    clientId: "668b4772-3c2e-4b86-98e0-04c58199cfe5"
  ai:
    deployment: "summary-agent"
  storage:
    accountName: "40xtujffdev"
    container: "flowforge-reports"
  postgres:
    host: "pgsql-40xtuj.postgres.database.azure.com"
    dbName: "flowforge-dev"
gateway:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/gateway
    tag: f1ad5ce
frontend:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/frontend
    tag: 47b4d87
auth-service:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/auth-service
    tag: 07f448b
project-service:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/project-service
    tag: 07f448b
task-service:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/task-service
    tag: 07f448b
analysis-service:
  enabled: true
  aiManagedIdentityClientId: "978c249b-1ac1-475a-9138-e96be1ec0f44"
  aiManagedIdentityName: "mi-ai-dev-m9mp04"
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/analysis-service
    tag: 6f3f897
notification-worker:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/notification-worker
    tag: f1ad5ce
