global:
  namespace: flowforge-prod
  environment: prod
  domain: flowforge.fun
  azure:
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
    keyvaultName: "kvlt-prod-22o4pc"
    keyvaultUrl: "https://kvlt-prod-22o4pc.vault.azure.net/"
    managedIdentityClientId: "1241e0e6-acb1-4fce-a606-52e82e015e7b"
  entra:
    clientId: "668b4772-3c2e-4b86-98e0-04c58199cfe5"
  ai:
    deployment: "summary-agent"
  storage:
    accountName: "22o4pcffprod"
gateway:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/gateway
    tag: latest
frontend:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/frontend
    tag: latest
auth-service:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/auth-service
    tag: latest
project-service:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/project-service
    tag: latest
task-service:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/task-service
    tag: latest
analysis-service:
  enabled: true
  aiManagedIdentityClientId: "41dd38b0-d0c6-4d0c-af2a-df8e6cf073e3"
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/analysis-service
    tag: latest
notification-worker:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/notification-worker
    tag: latest

