global:
  namespace: flowforge-dev
  environment: dev
  domain: dev.flowforge.fun
  azure:
    tenantId: "9b268e03-4db3-41c1-9c63-c106982f5abd"
    keyvaultName: "kvlt-dev-4r8ncj"
    keyvaultUrl: "https://kvlt-dev-4r8ncj.vault.azure.net/"
    managedIdentityClientId: "0d30ddbb-ec6a-4362-8031-198cf686f285"
  entra:
    clientId: "e2af85fb-72d9-457f-a9b8-84573d77242e"
  storage:
    accountName: "4r8ncjffdev"
gateway:
  enabled: true
  image:
    repository: flowforgeacr4r8ncj.azurecr.io/flowforge/gateway
    tag: 4e8e927
frontend:
  enabled: true
  image:
    repository: flowforgeacr4r8ncj.azurecr.io/flowforge/frontend
    tag: 90e5907
auth-service:
  enabled: true
  image:
    repository: flowforgeacr4r8ncj.azurecr.io/flowforge/auth-service
    tag: 90e5907
project-service:
  enabled: true
  image:
    repository: flowforgeacr4r8ncj.azurecr.io/flowforge/project-service
    tag: 4e8e927
task-service:
  enabled: true
  image:
    repository: flowforgeacr4r8ncj.azurecr.io/flowforge/task-service
    tag: 90e5907
analysis-service:
  enabled: true
  image:
    repository: flowforgeacr4r8ncj.azurecr.io/flowforge/analysis-service
    tag: 90e5907
notification-worker:
  enabled: true
  image:
    repository: flowforgeacr4r8ncj.azurecr.io/flowforge/notification-worker
    tag: 4e8e927
