global:
  namespace: flowforge-dev
  environment: dev
  domain: dev.flowforge.fun
  azure:
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
    keyvaultName: "kvlt-dev-m9mp04"
    keyvaultUrl: "https://kvlt-dev-m9mp04.vault.azure.net/"
    managedIdentityClientId: "4b6676e9-5bf5-4f04-b5b7-83cf166d1bf3"
  entra:
    clientId: "668b4772-3c2e-4b86-98e0-04c58199cfe5"
  storage:
    accountName: "m9mp04ffdev"
gateway:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/gateway
    tag: 8a3c80c
frontend:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/frontend
    tag: cc59c0e
auth-service:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/auth-service
    tag: 8a3c80c
project-service:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/project-service
    tag: 8a3c80c
task-service:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/task-service
    tag: 8a3c80c
analysis-service:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/analysis-service
    tag: 8a3c80c
notification-worker:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/notification-worker
    tag: 14e4191
