global:
  namespace: flowforge-prod
  environment: prod
  domain: flowforge.fun
  azure:
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
    keyvaultUrl: "https://kvlt-prod-40xtuj.vault.azure.net/"
    managedIdentityClientId: "1241e0e6-acb1-4fce-a606-52e82e015e7b"
    managedIdentityName: "mi-flowforge-app-prod"
  entra:
    clientId: "668b4772-3c2e-4b86-98e0-04c58199cfe5"
  ai:
    deployment: "summary-agent"
  storage:
    accountName: "40xtujffprod"
    container: "flowforge-reports"
  postgres:
    host: "pgsql-40xtuj.postgres.database.azure.com"
    dbName: "flowforge-prod"
gateway:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/gateway
    tag: v2.0.3
frontend:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/frontend
    tag: v2.0.4
auth-service:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/auth-service
    tag: v2.0.3
project-service:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/project-service
    tag: v2.0.3
task-service:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/task-service
    tag: v2.0.3
analysis-service:
  enabled: true
  aiManagedIdentityClientId: "41dd38b0-d0c6-4d0c-af2a-df8e6cf073e3"
  aiManagedIdentityName: "mi-ai-prod-m9mp04"
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/analysis-service
    tag: v2.0.3
notification-worker:
  enabled: true
  image:
    repository: flowforgeacrm9mp04.azurecr.io/flowforge/notification-worker
    tag: v2.0.3
