apiVersion: apps/v1
kind: Deployment
metadata:
  name: flowforge-notification-worker
  namespace: default
  labels:
    tier: worker
    app: flowforge-notification-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flowforge-notification-worker
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 50%
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
      labels:
        tier: worker
        app: flowforge-notification-worker
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: flowforge-notification-worker

      containers:
        - name: notification-worker
          image: "flowforgeacrm9mp04.azurecr.io/flowforge/notification-worker:14e4191"
          imagePullPolicy: IfNotPresent

          envFrom:
            - configMapRef:
                name: flowforge-config
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

      nodeSelector:
        agentpool: node1

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flowforge-notification-worker
  namespace: default
  annotations:
    azure.workload.identity/client-id: "4b6676e9-5bf5-4f04-b5b7-83cf166d1bf3"
automountServiceAccountToken: false
