apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- if .Values.aiManagedIdentityClientId }}
    azure.workload.identity/client-id: {{ .Values.aiManagedIdentityClientId | quote }}
    {{- end }}
