replicaCount: 1

image:
  repository: ghcr.io/noel-mathews-org/flowforge/auth-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 8001

resources:
  requests:
    cpu: 15m
    memory: 64Mi

hpa:
  minReplicas: 1
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70
